server:
  port: 8080
  mimeTypes: text/xml, text/css, text/html, application/json

spring:
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: springtest94
    password: tigran94
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false