server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:8889/job
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update